steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/sample-app:$SHORT_SHA', '.']
- name: 'debian'
  entrypoint: '/bin/bash'
  args: ['-c', "sed -i 's#gcr.io/project/image-name#gcr.io/$PROJECT_ID/sample-app#g' k8s/deploy/*"]
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', 'k8s/*', 'gs://$PROJECT_ID-kubernetes-manifests']
images: ['gcr.io/$PROJECT_ID/sample-app:$SHORT_SHA']


