
apiVersion: v1
kind: Service
metadata:
  name: app-service-canary
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
  selector: 
    role: app
    env: canary
